name: buckshot_html
description: >
  This is the HTML5 platform extension for the Buckshot core library.
version: 0.2.2
author: John Evans <prujohn@gmail.com>
homepage: http://www.buckshotui.org
dependencies:
  buckshot:
    git:
      url: git://github.com/prujohn/Buckshot.git
      ref: latest
  xml: 0.1.6
  dartnet_event_model: 0.2.0
  unittest: 0.2.7