name: buckshot_html
description: >
  This is the HTML5 platform extension for the Buckshot core library.
version: 0.2.2
author: John Evans <prujohn@gmail.com>
homepage: http://www.buckshotui.org
dependencies:
  buckshot:
    git:
      url: git://github.com/prujohn/Buckshot.git
      ref: latest
  xml:
    git: git://github.com/prujohn/dart-xml.git
  dartnet_event_model:
    git: git://github.com/prujohn/DartNet-Event-Model.git
  unittest: 0.2.7